### ISSUE TITLE
make logo div 50 percent 

### ISSUE THREAD

**Issue by rsgc-molloy-c** [rsgc-wrana-m/SSAS#16]

**Comment by rgordonathome** [comment]
The purpose of this issue is not clear – what does making a div element span 50% of the page width _accomplish_? That would be a more appropriate title for the issue.

Right now this doesn't seem like an edit that is significant enough to require a separate issue.

If it is a valid issue, please add an assignee and a label.

**Comment by rsgc-wrana-m** [comment]
Idea scrapped
